# Generated by Django 4.2.7 on 2025-05-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_deleted_by_recipient",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="is_deleted_by_sender",
            field=models.BooleanField(default=False),
        ),
    ]
