# Generated by Django 4.2.7 on 2025-05-18 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("real_estate_auth", "0004_contract"),
        ("messaging", "0002_message_is_deleted_by_recipient_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="real_estate_auth.contract",
            ),
        ),
    ]
