# Generated by Django 4.2.7 on 2025-05-17 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="currency",
            field=models.CharField(
                choices=[
                    ("COP", "Pesos Colombianos (COP)"),
                    ("USD", "Dólares Americanos (USD)"),
                ],
                default="COP",
                max_length=3,
            ),
        ),
    ]
