# Generated by Django 4.2.7 on 2025-05-18 19:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_property_currency"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                (
                    "profile_type",
                    models.CharField(
                        choices=[
                            ("arrendatario", "Arrendatario"),
                            ("arrendador", "Arrendador"),
                            ("prestador", "Prestador"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="property",
            name="available",
        ),
        migrations.RemoveField(
            model_name="property",
            name="photos",
        ),
        migrations.RemoveField(
            model_name="property",
            name="video",
        ),
        migrations.AddField(
            model_name="property",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("casa", "Casa"),
                    ("apartamento", "Apartamento"),
                    ("local", "Local"),
                    ("habitacion", "Habitación"),
                ],
                default="casa",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="property",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="propertyphoto",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="property",
            name="currency",
            field=models.CharField(
                choices=[("COP", "COP"), ("USD", "USD")], default="COP", max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="exact_address",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="propertyphoto",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="property_photos/"
            ),
        ),
    ]
