# Generated by Django 4.2.7 on 2025-05-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0003_interviewcode_remove_property_available_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Video de la propiedad (máximo 3 minutos)",
                null=True,
                upload_to="property_videos/",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="URL de video alternativa (YouTube o Vimeo)",
                null=True,
            ),
        ),
    ]
