# Generated by Django 4.2.7 on 2025-05-26 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0004_property_video_alter_property_video_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="bathrooms",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="bedrooms",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="construction_area",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="land_area",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="main_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="property_main_photos/"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="parking_spaces",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
