# Generated by Django 4.2.7 on 2025-05-26 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0005_property_bathrooms_property_bedrooms_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Video de la propiedad (máximo 3 minutos, formatos .mp4, .mov o .avi)",
                null=True,
                upload_to="property_videos/",
            ),
        ),
    ]
