# Generated by Django 4.2.7 on 2025-06-03 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0006_alter_property_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
