# Generated by Django 4.2.7 on 2025-06-03 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0007_property_latitude_property_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("casa", "Casa"),
                    ("apartamento", "Apartamento"),
                    ("local", "Local"),
                    ("habitacion", "Habitación"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
