# Generated by Django 4.2.7 on 2025-06-08 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0008_alter_property_property_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyphoto",
            name="is_main",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="propertyphoto",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
