# Generated by Django 4.2.7 on 2025-05-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("real_estate_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="phone number"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_pics/",
                verbose_name="profile picture",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_type",
            field=models.CharField(
                choices=[("buyer", "Buyer"), ("seller", "Seller"), ("agent", "Agent")],
                default="buyer",
                max_length=10,
                verbose_name="profile type",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="name",
            field=models.CharField(max_length=255, verbose_name="full name"),
        ),
    ]
