# Generated by Django 4.2.7 on 2025-05-12 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "real_estate_auth",
            "0002_customuser_phone_number_customuser_profile_picture_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ["-date_joined"],
                "verbose_name": "usuario",
                "verbose_name_plural": "usuarios",
            },
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                error_messages={
                    "unique": "Este correo electrónico ya está registrado."
                },
                max_length=254,
                unique=True,
                verbose_name="correo electrónico",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="name",
            field=models.CharField(
                help_text="Ingrese su nombre completo",
                max_length=255,
                verbose_name="nombre completo",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Número de contacto opcional",
                max_length=20,
                null=True,
                verbose_name="teléfono",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="Suba una imagen para su perfil",
                null=True,
                upload_to="profile_pics/",
                verbose_name="foto de perfil",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="profile_type",
            field=models.CharField(
                choices=[
                    ("arrendador", "Arrendador"),
                    ("arrendatario", "Arrendatario"),
                    ("prestador", "Prestador de Servicios"),
                ],
                default="arrendatario",
                help_text="Seleccione su rol en la plataforma",
                max_length=20,
                verbose_name="tipo de perfil",
            ),
        ),
    ]
