# Generated by Django 4.2.7 on 2025-05-18 15:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "real_estate_auth",
            "0003_alter_customuser_options_alter_customuser_email_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activo"),
                            ("terminated", "Terminado"),
                            ("pending", "Pendiente"),
                        ],
                        default="active",
                        max_length=50,
                    ),
                ),
                (
                    "parties",
                    models.ManyToManyField(
                        related_name="contracts", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "contrato",
                "verbose_name_plural": "contratos",
                "ordering": ["-created_at"],
            },
        ),
    ]
