# Generated by Django 4.2.7 on 2025-05-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("real_estate_auth", "0004_contract"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="interview_code",
            field=models.CharField(
                blank=True,
                help_text="Código asignado durante la entrevista por el administrador",
                max_length=10,
                null=True,
                unique=True,
                verbose_name="código de entrevista",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="rating",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Calificación de 1 a 5 asignada por el administrador",
                verbose_name="calificación inicial",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="resume",
            field=models.TextField(
                blank=True,
                help_text="Información de la hoja de vida",
                null=True,
                verbose_name="hoja de vida",
            ),
        ),
    ]
