# Generated by Django 4.2.7 on 2025-06-03 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "real_estate_auth",
            "0005_customuser_interview_code_customuser_rating_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_verified",
            field=models.BooleanField(
                default=False,
                help_text="Indica si el usuario ha sido verificado por un administrador",
                verbose_name="verificado",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="verification_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha en que el usuario fue verificado",
                null=True,
                verbose_name="fecha de verificación",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Administrador que verificó al usuario",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_users",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Verificado por",
            ),
        ),
        migrations.CreateModel(
            name="InterviewCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Código de entrevista"
                    ),
                ),
                (
                    "profile_type",
                    models.CharField(
                        choices=[
                            ("arrendador", "Arrendador"),
                            ("arrendatario", "Arrendatario"),
                            ("prestador", "Prestador de Servicios"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de perfil",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Calificación de 1 a 5 asignada por el administrador",
                        verbose_name="Calificación inicial",
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si el código ya ha sido utilizado para registrarse",
                        verbose_name="Utilizado",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Notas adicionales sobre la entrevista",
                        null=True,
                        verbose_name="Notas",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_codes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Código de entrevista",
                "verbose_name_plural": "Códigos de entrevista",
                "ordering": ["-created_at"],
            },
        ),
    ]
